- hosts: me
  gather_facts: false
  strategy: debug
  tasks:
    - name: Ensure file exists
      file: path=~/roster.txt state=file
    - name: Perform some dynamic includes
      loop: "{{roster}}"
      include_tasks: ~/ansible-class/tasks/roster-user-error.yaml
      vars:
        name: "{{item.student_name}}"
        email: "{{item.student_email}}"
        regexp: "{{item.student_email}}"
