- hosts: me
  become: yes
  tasks:
  - include_vars: users-vault.yaml
  - name: create user
    loop: "{{users}}"
    user:
        name: '{{item.username}}'
        password: "{{item.password}}"
        shell: /bin/bash
