- hosts: me
  become: true
  vars_prompt:
    - name: username
      prompt: What is your username?
  tasks:
  # - name: Let the sudo group use sudo without a password
  #   lineinfile: "dest=/etc/sudoers state=present regexp='^%sudo' line='%sudo ALL=(ALL) NOPASSWD: ALL'"
  - name: Let the sudo group use sudo without a password
    copy:
      src: ansible_sudoers
      dest: /etc/sudoers.d/ansible_sudoers
  - name: create user
    user:
        name: '{{username}}'
        groups: sudo
        shell: /bin/bash
  - name: Authorize the public key
    authorized_key:
      user: '{{username}}'
      state: present
      key: "{{lookup('file', '~/.ssh/authorized_keys')}}"