- hosts: me
  become: yes
  gather_facts: no
  vars_files:
    - users.yaml
    - users-vault.yaml
  tasks:
  - debug: var=users
  - name: create user
    loop: "{{users}}"
    user:
        name: '{{item.username}}'
        password: "{{item.password | password_hash('sha512', 'mysecretsalt') }}"
        shell: /bin/bash
