- hosts: me
  become: yes
  gather_facts: no
  tasks:
  - include_vars: users-vault.yaml
  - name: create user
    loop: "{{users}}"
    user:
        name: '{{item.username}}'
        password: "{{item.password | password_hash('sha512', 'mysecretsalt') }}"
        shell: /bin/bash
