- name: First play
  hosts: web
  remote_user: root
  tasks:
  - name: Say my name
    command: whoami
    notify: "demo handler"
    register: whoami_result
  - name: Show some vars
    debug:
      msg: I_am={{whoami_result.stdout}}
  - name: Get the system date and time
    command: date
    notify: "demo handler"
  - name: Ping just for fun
    ping:
  handlers:
  - name: demo handler
    command: 'echo Running the demo notify'
