- hosts: web
  become: true
  tasks:
    - name: Remove host from load balancer
      debug:
        msg: "This would probably be a custom module or the ec2_elb module"
      delegate_to: 127.0.0.1
    - name: Deploy some code
      debug:
        msg: "Hey, I'm deploying code!"
    - name: Re-add host to load balancer
      debug:
        msg: "This would probably be a custom module or the ec2_elb module"
      delegate_to: 127.0.0.1
