- hosts: web
  become: true
  tasks:
    - name: Remove host from load balancer
      local_action:
        module: debug
        msg: "This would probably be a custom module or the ec2_elb module"
    - name: Deploy some code
      debug:
        msg: "Hey, I'm deploying code!"
    - name: Re-add host to load balancer
      local_action:
        module: debug
        msg: "This would probably be a custom module or the ec2_elb module"
