- hosts: web
  become: true
  strategy: debug
  vars_prompt:
    - name: username
      prompt: What is your username?
  pre_tasks:
  - name: Ensure I am the correct user
    command: whoami
  - name: Ensure I have the correct username
    debug: var=username
  - name: Ensure public_html exists
    file: path=~{{username}}/public_html state=directory mode=755
  - name: Put a file in public_html
    file: path=~{{username}}/public_html/index.html state=touch mode=644
  - name: Put a message in the file
    lineinfile: line="Hello there {{username}}" dest=~{{username}}/public_html/index.html

  roles:
  - role: bennojoy.nginx
    become: on
    nginx_sites:
    - server:
        listen: 80
        file_name: "{{username}}-site"
        location1:
          name: "/"
          root: "/usr/share/nginx/html"
        location2:
          name: "/~{{username}}"
          alias: "/home/{{username}}/public_html"
          try_files: "$uri $uri/ /index.html"
    # item = {server: {listen: 80, file_name: "vagrant-site", location1: {...}, location2: {...}}}
