- hosts: web
  become: true
  become_user: rick
  pre_tasks:
  - name: Ensure I am the correct user
    command: whoami
  - name: Ensure I have the correct ansible_user
    debug: var=ansible_user
  - name: Ensure public_html exists
    file: path={{ansible_user}}/public_html state=directory mode=755
  - name: Put a file in public_html
    file: path={{ansible_user}}/public_html/index.html state=touch mode=644
  - name: Put a message in the file
    lineinfile: line="Hello there {{ansible_user}}" dest={{ansible_user}}/public_html/index.html

  roles:
  - role: bennojoy.nginx
    become: on
    become_user: root
    nginx_sites:
    - server:
        listen: 80
        file_name: "{{ansible_user}}-site"
        location1:
          name: "/"
          root: "/usr/share/nginx/html"
        location2:
          name: "/~{{ansible_user}}"
          alias: "/home/{{ansible_user}}/public_html"
          try_files: "$uri $uri/ /index.html"
    # item = {server: {listen: 80, file_name: "vagrant-site", location1: {...}, location2: {...}}}
