- hosts: web
  tasks:
    - name: Ensure file exists
      file: path=~/roster.txt state=file
    - name: Include rick
      import_tasks: ../tasks/roster-user.yaml name="Rick Copeland" email="rick@arborian.com" regexp=rick
