- hosts: web
  tasks:
    - name: Ensure file exists
      file: path=~/roster.txt state=touch
    - name: Include rick
      include_tasks: ../tasks/roster-user.yaml name="Rick Copeland" email="rick@arborian.com" regexp=opeland
