- hosts: web

  pre_tasks:
  - name: Ensure public_html exists
    file: path=~/public_html state=directory mode=755
  - name: Put a file in public_html
    file: path=~/public_html/index.html state=touch mode=644
  - name: Put a message in the file
    lineinfile: line="Hello there {{ansible_ssh_user}}" dest=~/public_html/index.html

  roles:
  - role: bennojoy.nginx
    become: on
    nginx_sites:
    - server:
        file_name: "vagrant-site"
        location1:
          name: "/"
          root: "/usr/share/nginx/html"
        location2:
          name: "/~vagrant"
          alias: "/home/vagrant/public_html"
          try_files: "$uri $uri/ /index.html"

  tasks:
    - debug: var=ansible_ssh_user