- hosts: web

  pre_tasks:
  - name: Ensure public_html exists
    file: path=~/public_html state=directory mode=755
  - name: Put a file in public_html
    file: path=~/public_html/index.html state=touch mode=644
  - name: Put a message in the file
    lineinfile: line="Hello there {{ansible_user}}" dest=~/public_html/index.html

  roles:
  - role: bennojoy.nginx
    become: on
    nginx_sites:
    - server:
        listen: 80
        file_name: "{{ansible_user}}-site"
        location1:
          name: "/"
          root: "/usr/share/nginx/html"
        location2:
          name: "/~{{ansible_user}}"
          alias: "/home/{{ansible_user}}/public_html"
          try_files: "$uri $uri/ /index.html"

