- hosts: all
  serial:
    - 1
    - 2
    - 100%
  tasks:
    - name: Remove from the load balancer
      local_action:
        module: debug
        var: ansible_host
    - name: Deploy code
      debug: var=ansible_host
    - name: Add to the load balancer
      local_action:
        module: debug
        var: ansible_host
