- hosts: web
  become: true
  roles:
    - role: bennojoy.nginx
      nginx_http_params:
        sendfile: 'on'
        access_log: /var/log/nginx/access.log'
      nginx_sites:
       - server:
          file_name: foo
          listen: 8080
          server_name: localhost
          root: '/tmp/site1'
          location1: {name: /, try_files: '$uri $uri/ /index.html'}
          location2: {name: /images/, try_files: '$uri $uri/ /index.html'}
       - server:
          file_name: bar
          listen: 9090
          server_name: ansible
          root: '/tmp/site2'
          location1: {name: /, try_files: '$uri $uri/ /index.html'}
          location2: {name: /images/, try_files: '$uri $uri/ /index.html'}