- hosts: me
  become: yes
  vars:
    username: ansible-is-so-awesome
    mygroups: 
        - wheel
  tasks:
  - name: create user
    user:
        name: '{{username}}'
        groups: '{{mygroups}}'
        generate_ssh_key: yes
        shell: /bin/bash
