- hosts: web
  become: true
  roles:
    - role: bennojoy.nginx
- hosts: db
  become: true
  ignore_errors: true
  roles:
    - role: geerlingguy.mysql
      become: yes
- hosts: app
  become: true
  roles:
    - role: geerlingguy.jenkins