- hosts: arborian-01.class.arborian.com
  tasks:
    - name: Run whoami
      command: whoami
      register: cabbage
    - name: Print a message
      debug:
        var: cabbage
    - name: Another message
      debug:
        msg: If you were wondering, I am {{cabbage.stdout}}