- hosts: web
  vars:
    num_sites: 4
  tasks:
    - name: Install supervisor
      become: true
      apt:
        name: supervisor
        state: installed
        force: true
    - name: Create directory
      file:
        path: /home/vagrant/test{{item}}
        state: directory
      with_sequence: start=0 count={{num_sites}}
      notify: reload supervisor config
    - name: Create config
      become: true
      webserver:
        name: test{{item}}
        path: /home/vagrant/test{{item}}
        port: "{{8000 + (item|int)}}"
      with_sequence: start=0 count={{num_sites}}
      notify: reload supervisor config
  handlers:
    - name: reload supervisor config
      become: true
      command: supervisorctl reload
