- hosts: all
  become: true
  vars:
    username: rick
  tasks:
  - name: Let the sudo group use sudo without a password
    lineinfile: "dest=/etc/sudoers state=present regexp='^%sudo' line='%sudo ALL=(ALL) NOPASSWD: ALL'"
  - name: create user
    user:
        name: '{{username}}'
        groups: sudo
        shell: /bin/bash
  - name: Authorize the public key
    authorized_key:
      user: '{{username}}'
      state: present
      key: https://raw.githubusercontent.com/Arborian/ansible-class/master/training-ssh-key.pub
