- hosts: localhost
  gather_facts: false
  vars_files:
    - ../rsa.yaml
  tasks:
  # - name: Decrypt the RSA key
  #   include_vars: ../rsa.yaml
  - name: Save the key
    copy: dest=../id_rsa content={{id_rsa}} mode=600
  - debug: var=something_else